spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.25.228.187:3306/myproject?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.demo.bean
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql #设置数据库类型
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
  #可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql
  reasonable: true #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页

logging:
  level:
    com.springboot.demo.dao: debug